version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_DATABASE_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"
